name: BayesianStellarEvolution
category: application
author: Elliot Robinson
maintainer: elliot.robinson@rgoptech.com
copyright: '2019'
# license:
github: BayesianStellarEvolution/BayesianStellarEvolution

default-extensions:
  - OverloadedStrings
  - BangPatterns

ghc-options:
  - -Wall
  
library:
  source-dirs: src
  exposed-modules:
    - Cluster
    - MainSequenceModel
    - Options
    - Output.Sql
    - Paths
    - Models.Input
    - Models.Interpolate
dependencies:
    - base >=4.10 && <5
    - attoparsec
    - bytestring
    - conduit
    - conduit-extra
    - containers
    - lzma-conduit
    - vector

executables:
  makeIsochrone:
    main: Main.hs
    source-dirs: makeIsochrone
    dependencies:
      - base
      - BayesianStellarEvolution
      - data-default
      - cmdargs

  plotIsochrones:
    main: Main.hs
    source-dirs: plotIsochrones
    dependencies:
      - base
      - attoparsec
      - BayesianStellarEvolution
      - bytestring
      - Chart
      - Chart-cairo
      - containers
      - lzma-conduit
      - vector

tests:
  library-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - attoparsec
      - bytestring
      - conduit
      - BayesianStellarEvolution
      - hspec
      - QuickCheck
      - raw-strings-qq
      - vector
