name: base
category: application
author: Elliot Robinson
maintainer: elliot.robinson@rgoptech.com
copyright: '2019'
# license:
github: BayesianStellarEvolution/base

library:
  source-dirs: src
  exposed-modules: []
  dependencies:
    - base >=4.12 && <5
