name: BayesianStellarEvolution
category: application
author: Elliot Robinson
maintainer: elliot.robinson@rgoptech.com
copyright: '2019'
# license:
github: BayesianStellarEvolution/BayesianStellarEvolution

default-extensions:
  - OverloadedStrings
  - BangPatterns

ghc-options:
  - -Wall
  
library:
  source-dirs: src
  exposed-modules:
    - Magnitude
    - Models.Input
    - Models.Sample
    - Interpolate
    - Types
dependencies:
    - base >=4.10 && <5
    - BayesianStellarEvolution-Models
    - attoparsec
    - bytestring
    - conduit
    - conduit-extra
    - containers
    - ghc-compact
    - lzma-conduit
    - math-functions
    - optparse-applicative
    - QuickCheck
    - text
    - vector
    - vector-th-unbox

executables:
  makeIsochrone:
    main: Main.hs
    source-dirs: makeIsochrone
    dependencies:
      - base
      - BayesianStellarEvolution
      - containers
      - optparse-applicative
      - vector

tests:
  library-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - BayesianStellarEvolution
      - attoparsec
      - bytestring
      - conduit
      - containers
      - hspec
      - QuickCheck
      - raw-strings-qq
      - vector


benchmarks:
  library-benchmarks:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - BayesianStellarEvolution
      - criterion
      - vector
 
