name: BayesianStellarEvolution
category: application
author: Elliot Robinson
maintainer: elliot.robinson@rgoptech.com
copyright: '2019'
# license:
github: BayesianStellarEvolution/BayesianStellarEvolution

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
    - MainSequenceModel
  dependencies:
    - base >=4.12 && <5
    - attoparsec
    - conduit
    - conduit-extra
    - text

executables:
  makeIsochrone:
    main: Main.hs
    source-dirs: makeIsochrone
    dependencies:
      - base
      - BayesianStellarEvolution
    
tests:
  library-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - attoparsec
      - BayesianStellarEvolution
      - hspec
      - QuickCheck
      - raw-strings-qq
      - text
