name: BayesianStellarEvolution-Models
category: application
author: Elliot Robinson
maintainer: elliot.robinson@rgoptech.com
copyright: '2019'
# license:
github: BayesianStellarEvolution/BayesianStellarEvolution

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
    - MainSequenceModel
    - Paths
dependencies:
    - base >=4.10 && <5
    - attoparsec
    - bytestring
    - conduit
    - conduit-extra
    - containers
    - lzma-conduit
    - text
    - vector

executables:
  testModelArchive:                                                                                   
    main: Main.hs
    source-dirs: testModelArchive
    dependencies:
      - base

tests:
  model-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
    dependencies:
      - base
      - BayesianStellarEvolution-Models

      - attoparsec
      - bytestring
      - conduit
      - conduit-extra
      - hspec
      - lzma-conduit
      - QuickCheck
      - raw-strings-qq
      - vector
